#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use App\Test;

$reflector = new \ReflectionClass(Test::class);
$methods = $reflector->getMethods();
$classToMigrateFile = __DIR__ . '/Test.php';
$classToMigrate = \file_get_contents($classToMigrateFile);
$factory = \phpDocumentor\Reflection\DocBlockFactory::createInstance();

foreach ($methods as $method) {
    $matches = [];

    $docBlock = $factory->create($method->getDocComment());
    $params = $docBlock->getTagsByName('param');
    $returns = $docBlock->getTagsByName('return');
    $pattern = '/' . $method->getName() . '\(.+\)' . '/';
    \preg_match($pattern, $classToMigrate, $matches);
    $methodSignature = $matches[0];
    $oldMethodSignature = $methodSignature;
    $typeParams = buildType($params);
    $paramsName = buildParam($params);
    $combineParamType = \array_combine($paramsName,  $typeParams);

    foreach ($combineParamType as $paramName => $type) {
        $methodSignature = \str_replace($paramName, $type . ' ' . $paramName, $methodSignature);
    }

    $typeReturns = buildType($returns);

    foreach ($typeReturns as $return) {
        $methodSignature = \str_replace(')', ') : '.$return, $methodSignature);
    }

    $classToMigrate = \str_replace($oldMethodSignature, $methodSignature, $classToMigrate);
}

\file_put_contents($classToMigrateFile, $classToMigrate);



function buildType($arrayType) {
     $allType = [];
    foreach ($arrayType as $type) {
        $type = (string) $type->getType();
        $types = \explode('|', $type);
        $typesNum = \count($types);

        if ($typesNum > 2) {
            continue;
        } elseif ($typesNum === 2 && in_array('null', $types)) {
            $type = '?' . ($types[0] === 'null' ? $types[1] : $types[0]);
        }
         $allType[] = $type;
    }
    return $allType;
}

function buildParam($params) {
    $vars = [];
    foreach ($params as $param) {
        $paramName = '$' . $param->getVariableName();
        $vars[] = $paramName;
    }
    return $vars;
}